import type { PlayerColor } from "@/lib/sources/types";

export interface CatalogEntry {
  id: string;
  name: string;
  family: string;
  color: PlayerColor;
  eco: string;
  /**
   * SAN moves from ply 1 (white's first move). Prefix match for classification —
   * longest prefix wins. Keep sequences short enough to absorb typical move-order
   * transpositions at the popular lines.
   */
  moves: string[];
  /** Rough subjective popularity, 0–100. Drives gap-analysis recommendations. */
  popularity: number;
}

// ────────────────────────────────────────────────────────────────────────────
// WHITE repertoire
// ────────────────────────────────────────────────────────────────────────────

const WHITE_E4: CatalogEntry[] = [
  // 1.e4 e5
  {
    id: "w-open-game",
    name: "Open Game",
    family: "1.e4 e5",
    color: "white",
    eco: "C20",
    moves: ["e4", "e5"],
    popularity: 70,
  },
  {
    id: "w-italian",
    name: "Italian Game",
    family: "1.e4 e5",
    color: "white",
    eco: "C50",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bc4"],
    popularity: 88,
  },
  {
    id: "w-italian-giuoco",
    name: "Italian, Giuoco Piano",
    family: "1.e4 e5",
    color: "white",
    eco: "C50",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Bc5"],
    popularity: 72,
  },
  {
    id: "w-italian-two-knights",
    name: "Italian, Two Knights",
    family: "1.e4 e5",
    color: "white",
    eco: "C55",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6"],
    popularity: 66,
  },
  {
    id: "w-italian-evans",
    name: "Evans Gambit",
    family: "1.e4 e5",
    color: "white",
    eco: "C51",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Bc5", "b4"],
    popularity: 22,
  },
  {
    id: "w-ruy-lopez",
    name: "Ruy López",
    family: "1.e4 e5",
    color: "white",
    eco: "C60",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bb5"],
    popularity: 90,
  },
  {
    id: "w-ruy-berlin",
    name: "Ruy López, Berlin",
    family: "1.e4 e5",
    color: "white",
    eco: "C65",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bb5", "Nf6"],
    popularity: 68,
  },
  {
    id: "w-ruy-closed",
    name: "Ruy López, Closed",
    family: "1.e4 e5",
    color: "white",
    eco: "C84",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bb5", "a6", "Ba4"],
    popularity: 78,
  },
  {
    id: "w-ruy-exchange",
    name: "Ruy López, Exchange",
    family: "1.e4 e5",
    color: "white",
    eco: "C68",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bb5", "a6", "Bxc6"],
    popularity: 48,
  },
  {
    id: "w-scotch",
    name: "Scotch Game",
    family: "1.e4 e5",
    color: "white",
    eco: "C44",
    moves: ["e4", "e5", "Nf3", "Nc6", "d4"],
    popularity: 55,
  },
  {
    id: "w-scotch-gambit",
    name: "Scotch Gambit",
    family: "1.e4 e5",
    color: "white",
    eco: "C44",
    moves: ["e4", "e5", "Nf3", "Nc6", "d4", "exd4", "Bc4"],
    popularity: 30,
  },
  {
    id: "w-kings-gambit",
    name: "King's Gambit",
    family: "1.e4 e5",
    color: "white",
    eco: "C30",
    moves: ["e4", "e5", "f4"],
    popularity: 30,
  },
  {
    id: "w-vienna",
    name: "Vienna Game",
    family: "1.e4 e5",
    color: "white",
    eco: "C25",
    moves: ["e4", "e5", "Nc3"],
    popularity: 42,
  },
  // vs Sicilian
  {
    id: "w-open-sicilian",
    name: "Open Sicilian",
    family: "vs Sicilian",
    color: "white",
    eco: "B56",
    moves: ["e4", "c5", "Nf3"],
    popularity: 78,
  },
  {
    id: "w-bb5-antisicilian",
    name: "Bb5 Anti-Sicilian",
    family: "vs Sicilian",
    color: "white",
    eco: "B30",
    moves: ["e4", "c5", "Nf3", "Nc6", "Bb5"],
    popularity: 62,
  },
  {
    id: "w-moscow",
    name: "Moscow Variation",
    family: "vs Sicilian",
    color: "white",
    eco: "B51",
    moves: ["e4", "c5", "Nf3", "d6", "Bb5+"],
    popularity: 54,
  },
  {
    id: "w-alapin",
    name: "Alapin Sicilian",
    family: "vs Sicilian",
    color: "white",
    eco: "B22",
    moves: ["e4", "c5", "c3"],
    popularity: 58,
  },
  {
    id: "w-grand-prix",
    name: "Grand Prix Attack",
    family: "vs Sicilian",
    color: "white",
    eco: "B23",
    moves: ["e4", "c5", "Nc3"],
    popularity: 30,
  },
  {
    id: "w-closed-sicilian",
    name: "Closed Sicilian",
    family: "vs Sicilian",
    color: "white",
    eco: "B25",
    moves: ["e4", "c5", "Nc3", "Nc6", "g3"],
    popularity: 22,
  },
  {
    id: "w-smith-morra",
    name: "Smith-Morra Gambit",
    family: "vs Sicilian",
    color: "white",
    eco: "B21",
    moves: ["e4", "c5", "d4"],
    popularity: 24,
  },
  // vs French
  {
    id: "w-vs-french",
    name: "vs French",
    family: "vs French",
    color: "white",
    eco: "C00",
    moves: ["e4", "e6"],
    popularity: 70,
  },
  {
    id: "w-french-advance",
    name: "French, Advance",
    family: "vs French",
    color: "white",
    eco: "C02",
    moves: ["e4", "e6", "d4", "d5", "e5"],
    popularity: 55,
  },
  {
    id: "w-french-tarrasch",
    name: "French, Tarrasch",
    family: "vs French",
    color: "white",
    eco: "C03",
    moves: ["e4", "e6", "d4", "d5", "Nd2"],
    popularity: 48,
  },
  {
    id: "w-french-exchange",
    name: "French, Exchange",
    family: "vs French",
    color: "white",
    eco: "C01",
    moves: ["e4", "e6", "d4", "d5", "exd5"],
    popularity: 28,
  },
  {
    id: "w-french-classical",
    name: "French, Classical",
    family: "vs French",
    color: "white",
    eco: "C11",
    moves: ["e4", "e6", "d4", "d5", "Nc3", "Nf6"],
    popularity: 44,
  },
  {
    id: "w-french-winawer",
    name: "French, Winawer",
    family: "vs French",
    color: "white",
    eco: "C15",
    moves: ["e4", "e6", "d4", "d5", "Nc3", "Bb4"],
    popularity: 40,
  },
  // vs Caro-Kann
  {
    id: "w-vs-caro",
    name: "vs Caro-Kann",
    family: "vs Caro-Kann",
    color: "white",
    eco: "B10",
    moves: ["e4", "c6"],
    popularity: 68,
  },
  {
    id: "w-caro-advance",
    name: "Caro-Kann, Advance",
    family: "vs Caro-Kann",
    color: "white",
    eco: "B12",
    moves: ["e4", "c6", "d4", "d5", "e5"],
    popularity: 58,
  },
  {
    id: "w-caro-classical",
    name: "Caro-Kann, Classical",
    family: "vs Caro-Kann",
    color: "white",
    eco: "B18",
    moves: ["e4", "c6", "d4", "d5", "Nc3", "dxe4", "Nxe4", "Bf5"],
    popularity: 44,
  },
  {
    id: "w-caro-panov",
    name: "Caro-Kann, Panov Attack",
    family: "vs Caro-Kann",
    color: "white",
    eco: "B13",
    moves: ["e4", "c6", "d4", "d5", "exd5", "cxd5", "c4"],
    popularity: 38,
  },
  {
    id: "w-caro-exchange",
    name: "Caro-Kann, Exchange",
    family: "vs Caro-Kann",
    color: "white",
    eco: "B13",
    moves: ["e4", "c6", "d4", "d5", "exd5", "cxd5", "Bd3"],
    popularity: 30,
  },
  // vs Pirc / Modern / Scandinavian / Alekhine
  {
    id: "w-vs-pirc",
    name: "vs Pirc",
    family: "vs Pirc / Modern",
    color: "white",
    eco: "B07",
    moves: ["e4", "d6", "d4", "Nf6"],
    popularity: 40,
  },
  {
    id: "w-pirc-austrian",
    name: "Pirc, Austrian Attack",
    family: "vs Pirc / Modern",
    color: "white",
    eco: "B09",
    moves: ["e4", "d6", "d4", "Nf6", "Nc3", "g6", "f4"],
    popularity: 28,
  },
  {
    id: "w-vs-modern",
    name: "vs Modern",
    family: "vs Pirc / Modern",
    color: "white",
    eco: "B06",
    moves: ["e4", "g6"],
    popularity: 34,
  },
  {
    id: "w-vs-scandinavian",
    name: "vs Scandinavian",
    family: "vs Scandinavian",
    color: "white",
    eco: "B01",
    moves: ["e4", "d5", "exd5"],
    popularity: 40,
  },
  {
    id: "w-vs-alekhine",
    name: "vs Alekhine",
    family: "vs Alekhine",
    color: "white",
    eco: "B02",
    moves: ["e4", "Nf6", "e5", "Nd5"],
    popularity: 30,
  },
];

const WHITE_D4: CatalogEntry[] = [
  // London
  {
    id: "w-london",
    name: "London System",
    family: "London",
    color: "white",
    eco: "D02",
    moves: ["d4", "d5", "Nf3", "Nf6", "Bf4"],
    popularity: 92,
  },
  {
    id: "w-london-vs-kid",
    name: "London vs KID setup",
    family: "London",
    color: "white",
    eco: "A48",
    moves: ["d4", "Nf6", "Nf3", "g6", "Bf4"],
    popularity: 60,
  },
  {
    id: "w-jobava",
    name: "Jobava London",
    family: "London",
    color: "white",
    eco: "D00",
    moves: ["d4", "Nf6", "Nc3", "d5", "Bf4"],
    popularity: 36,
  },
  // Queen's Pawn
  {
    id: "w-queens-gambit",
    name: "Queen's Gambit",
    family: "Queen's Gambit",
    color: "white",
    eco: "D06",
    moves: ["d4", "d5", "c4"],
    popularity: 82,
  },
  {
    id: "w-qga-white",
    name: "Queen's Gambit Accepted",
    family: "Queen's Gambit",
    color: "white",
    eco: "D20",
    moves: ["d4", "d5", "c4", "dxc4"],
    popularity: 48,
  },
  {
    id: "w-qgd-exchange",
    name: "QGD, Exchange",
    family: "Queen's Gambit",
    color: "white",
    eco: "D35",
    moves: ["d4", "d5", "c4", "e6", "cxd5"],
    popularity: 46,
  },
  {
    id: "w-qgd-orthodox",
    name: "QGD, Orthodox",
    family: "Queen's Gambit",
    color: "white",
    eco: "D50",
    moves: ["d4", "d5", "c4", "e6", "Nc3", "Nf6", "Bg5"],
    popularity: 54,
  },
  {
    id: "w-slav-exchange",
    name: "Slav, Exchange",
    family: "Queen's Gambit",
    color: "white",
    eco: "D10",
    moves: ["d4", "d5", "c4", "c6", "cxd5"],
    popularity: 32,
  },
  {
    id: "w-slav-main",
    name: "Slav, Main Line",
    family: "Queen's Gambit",
    color: "white",
    eco: "D11",
    moves: ["d4", "d5", "c4", "c6", "Nf3", "Nf6"],
    popularity: 52,
  },
  // Indians (White side)
  {
    id: "w-trompowsky",
    name: "Trompowsky Attack",
    family: "1.d4 Nf6",
    color: "white",
    eco: "A45",
    moves: ["d4", "Nf6", "Bg5"],
    popularity: 42,
  },
  {
    id: "w-torre",
    name: "Torre Attack",
    family: "1.d4 Nf6",
    color: "white",
    eco: "A46",
    moves: ["d4", "Nf6", "Nf3", "e6", "Bg5"],
    popularity: 32,
  },
  {
    id: "w-catalan",
    name: "Catalan",
    family: "vs Indian",
    color: "white",
    eco: "E00",
    moves: ["d4", "Nf6", "c4", "e6", "g3"],
    popularity: 58,
  },
  {
    id: "w-nimzo-white",
    name: "Nimzo-Indian (White)",
    family: "vs Indian",
    color: "white",
    eco: "E20",
    moves: ["d4", "Nf6", "c4", "e6", "Nc3", "Bb4"],
    popularity: 58,
  },
  {
    id: "w-queens-indian-white",
    name: "Queen's Indian (White)",
    family: "vs Indian",
    color: "white",
    eco: "E12",
    moves: ["d4", "Nf6", "c4", "e6", "Nf3", "b6"],
    popularity: 40,
  },
  {
    id: "w-kid-classical",
    name: "KID, Classical (White)",
    family: "vs Indian",
    color: "white",
    eco: "E90",
    moves: ["d4", "Nf6", "c4", "g6", "Nc3", "Bg7", "e4"],
    popularity: 58,
  },
  {
    id: "w-kid-saemisch",
    name: "KID, Sämisch",
    family: "vs Indian",
    color: "white",
    eco: "E80",
    moves: ["d4", "Nf6", "c4", "g6", "Nc3", "Bg7", "e4", "d6", "f3"],
    popularity: 22,
  },
  {
    id: "w-grunfeld-white",
    name: "Grünfeld (White)",
    family: "vs Indian",
    color: "white",
    eco: "D80",
    moves: ["d4", "Nf6", "c4", "g6", "Nc3", "d5"],
    popularity: 50,
  },
  {
    id: "w-benoni-white",
    name: "Benoni (White)",
    family: "vs Indian",
    color: "white",
    eco: "A60",
    moves: ["d4", "Nf6", "c4", "c5", "d5"],
    popularity: 30,
  },
  // vs Dutch
  {
    id: "w-vs-dutch",
    name: "vs Dutch",
    family: "vs Dutch",
    color: "white",
    eco: "A80",
    moves: ["d4", "f5"],
    popularity: 28,
  },
  // Systems
  {
    id: "w-colle",
    name: "Colle System",
    family: "1.d4",
    color: "white",
    eco: "D05",
    moves: ["d4", "d5", "Nf3", "Nf6", "e3"],
    popularity: 32,
  },
];

const WHITE_OTHER: CatalogEntry[] = [
  {
    id: "w-reti",
    name: "Réti Opening",
    family: "Flank",
    color: "white",
    eco: "A09",
    moves: ["Nf3", "d5", "c4"],
    popularity: 50,
  },
  {
    id: "w-kia",
    name: "King's Indian Attack",
    family: "Flank",
    color: "white",
    eco: "A07",
    moves: ["Nf3", "d5", "g3"],
    popularity: 38,
  },
  {
    id: "w-english",
    name: "English Opening",
    family: "Flank",
    color: "white",
    eco: "A10",
    moves: ["c4"],
    popularity: 62,
  },
  {
    id: "w-bird",
    name: "Bird's Opening",
    family: "Flank",
    color: "white",
    eco: "A02",
    moves: ["f4"],
    popularity: 25,
  },
];

// ────────────────────────────────────────────────────────────────────────────
// BLACK repertoire
// ────────────────────────────────────────────────────────────────────────────

const BLACK_VS_E4: CatalogEntry[] = [
  {
    id: "b-e5",
    name: "1…e5 (Open Game)",
    family: "vs 1.e4",
    color: "black",
    eco: "C20",
    moves: ["e4", "e5"],
    popularity: 80,
  },
  {
    id: "b-petrov",
    name: "Petrov Defence",
    family: "1…e5",
    color: "black",
    eco: "C42",
    moves: ["e4", "e5", "Nf3", "Nf6"],
    popularity: 48,
  },
  {
    id: "b-philidor",
    name: "Philidor Defence",
    family: "1…e5",
    color: "black",
    eco: "C41",
    moves: ["e4", "e5", "Nf3", "d6"],
    popularity: 30,
  },
  {
    id: "b-italian-black",
    name: "Italian (Black)",
    family: "1…e5",
    color: "black",
    eco: "C50",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Bc5"],
    popularity: 60,
  },
  {
    id: "b-two-knights-black",
    name: "Two Knights (Black)",
    family: "1…e5",
    color: "black",
    eco: "C55",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6"],
    popularity: 50,
  },
  {
    id: "b-ruy-berlin-black",
    name: "Ruy López, Berlin (Black)",
    family: "1…e5",
    color: "black",
    eco: "C65",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bb5", "Nf6"],
    popularity: 64,
  },
  {
    id: "b-ruy-morphy-black",
    name: "Ruy López, Morphy (Black)",
    family: "1…e5",
    color: "black",
    eco: "C70",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bb5", "a6"],
    popularity: 70,
  },
  {
    id: "b-caro-kann",
    name: "Caro-Kann",
    family: "vs 1.e4",
    color: "black",
    eco: "B10",
    moves: ["e4", "c6"],
    popularity: 82,
  },
  {
    id: "b-sicilian",
    name: "Sicilian (generic)",
    family: "Sicilian",
    color: "black",
    eco: "B20",
    moves: ["e4", "c5"],
    popularity: 90,
  },
  {
    id: "b-sicilian-najdorf",
    name: "Sicilian, Najdorf",
    family: "Sicilian",
    color: "black",
    eco: "B90",
    moves: [
      "e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "a6",
    ],
    popularity: 78,
  },
  {
    id: "b-sicilian-dragon",
    name: "Sicilian, Dragon",
    family: "Sicilian",
    color: "black",
    eco: "B70",
    moves: [
      "e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "g6",
    ],
    popularity: 55,
  },
  {
    id: "b-sicilian-sveshnikov",
    name: "Sicilian, Sveshnikov",
    family: "Sicilian",
    color: "black",
    eco: "B33",
    moves: [
      "e4", "c5", "Nf3", "Nc6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "e5",
    ],
    popularity: 62,
  },
  {
    id: "b-sicilian-kan",
    name: "Sicilian, Kan",
    family: "Sicilian",
    color: "black",
    eco: "B42",
    moves: ["e4", "c5", "Nf3", "e6", "d4", "cxd4", "Nxd4", "a6"],
    popularity: 45,
  },
  {
    id: "b-sicilian-accelerated-dragon",
    name: "Sicilian, Accelerated Dragon",
    family: "Sicilian",
    color: "black",
    eco: "B34",
    moves: ["e4", "c5", "Nf3", "Nc6", "d4", "cxd4", "Nxd4", "g6"],
    popularity: 40,
  },
  {
    id: "b-sicilian-scheveningen",
    name: "Sicilian, Scheveningen",
    family: "Sicilian",
    color: "black",
    eco: "B80",
    moves: [
      "e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "e6",
    ],
    popularity: 38,
  },
  {
    id: "b-sicilian-classical",
    name: "Sicilian, Classical",
    family: "Sicilian",
    color: "black",
    eco: "B56",
    moves: [
      "e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "Nc6",
    ],
    popularity: 32,
  },
  {
    id: "b-french",
    name: "French Defence",
    family: "vs 1.e4",
    color: "black",
    eco: "C00",
    moves: ["e4", "e6"],
    popularity: 72,
  },
  {
    id: "b-french-advance",
    name: "French, Advance (Black)",
    family: "French",
    color: "black",
    eco: "C02",
    moves: ["e4", "e6", "d4", "d5", "e5"],
    popularity: 48,
  },
  {
    id: "b-french-winawer",
    name: "French, Winawer (Black)",
    family: "French",
    color: "black",
    eco: "C15",
    moves: ["e4", "e6", "d4", "d5", "Nc3", "Bb4"],
    popularity: 44,
  },
  {
    id: "b-french-classical",
    name: "French, Classical (Black)",
    family: "French",
    color: "black",
    eco: "C11",
    moves: ["e4", "e6", "d4", "d5", "Nc3", "Nf6"],
    popularity: 40,
  },
  {
    id: "b-caro-advance",
    name: "Caro-Kann, Advance (Black)",
    family: "Caro-Kann",
    color: "black",
    eco: "B12",
    moves: ["e4", "c6", "d4", "d5", "e5"],
    popularity: 56,
  },
  {
    id: "b-caro-classical-black",
    name: "Caro-Kann, Classical (Black)",
    family: "Caro-Kann",
    color: "black",
    eco: "B18",
    moves: ["e4", "c6", "d4", "d5", "Nc3", "dxe4", "Nxe4", "Bf5"],
    popularity: 48,
  },
  {
    id: "b-pirc",
    name: "Pirc Defence",
    family: "vs 1.e4",
    color: "black",
    eco: "B07",
    moves: ["e4", "d6"],
    popularity: 45,
  },
  {
    id: "b-modern",
    name: "Modern Defence",
    family: "vs 1.e4",
    color: "black",
    eco: "B06",
    moves: ["e4", "g6"],
    popularity: 35,
  },
  {
    id: "b-scandinavian",
    name: "Scandinavian Defence",
    family: "vs 1.e4",
    color: "black",
    eco: "B01",
    moves: ["e4", "d5"],
    popularity: 52,
  },
  {
    id: "b-alekhine",
    name: "Alekhine Defence",
    family: "vs 1.e4",
    color: "black",
    eco: "B02",
    moves: ["e4", "Nf6"],
    popularity: 32,
  },
];

const BLACK_VS_D4: CatalogEntry[] = [
  {
    id: "b-kid",
    name: "King's Indian Defence",
    family: "Indian",
    color: "black",
    eco: "E60",
    moves: ["d4", "Nf6", "c4", "g6"],
    popularity: 70,
  },
  {
    id: "b-kid-classical",
    name: "KID, Classical",
    family: "Indian",
    color: "black",
    eco: "E90",
    moves: ["d4", "Nf6", "c4", "g6", "Nc3", "Bg7", "e4", "d6"],
    popularity: 60,
  },
  {
    id: "b-grunfeld",
    name: "Grünfeld Defence",
    family: "Indian",
    color: "black",
    eco: "D80",
    moves: ["d4", "Nf6", "c4", "g6", "Nc3", "d5"],
    popularity: 60,
  },
  {
    id: "b-nimzo-indian",
    name: "Nimzo-Indian",
    family: "Indian",
    color: "black",
    eco: "E20",
    moves: ["d4", "Nf6", "c4", "e6", "Nc3", "Bb4"],
    popularity: 72,
  },
  {
    id: "b-nimzo-rubinstein",
    name: "Nimzo-Indian, Rubinstein",
    family: "Indian",
    color: "black",
    eco: "E40",
    moves: ["d4", "Nf6", "c4", "e6", "Nc3", "Bb4", "e3"],
    popularity: 50,
  },
  {
    id: "b-nimzo-classical",
    name: "Nimzo-Indian, Classical",
    family: "Indian",
    color: "black",
    eco: "E32",
    moves: ["d4", "Nf6", "c4", "e6", "Nc3", "Bb4", "Qc2"],
    popularity: 46,
  },
  {
    id: "b-queens-indian",
    name: "Queen's Indian",
    family: "Indian",
    color: "black",
    eco: "E12",
    moves: ["d4", "Nf6", "c4", "e6", "Nf3", "b6"],
    popularity: 48,
  },
  {
    id: "b-bogo-indian",
    name: "Bogo-Indian",
    family: "Indian",
    color: "black",
    eco: "E11",
    moves: ["d4", "Nf6", "c4", "e6", "Nf3", "Bb4+"],
    popularity: 30,
  },
  {
    id: "b-qgd",
    name: "Queen's Gambit Declined",
    family: "Queen's Pawn",
    color: "black",
    eco: "D30",
    moves: ["d4", "d5", "c4", "e6"],
    popularity: 82,
  },
  {
    id: "b-qgd-orthodox",
    name: "QGD, Orthodox",
    family: "Queen's Pawn",
    color: "black",
    eco: "D50",
    moves: ["d4", "d5", "c4", "e6", "Nc3", "Nf6", "Bg5"],
    popularity: 60,
  },
  {
    id: "b-slav",
    name: "Slav Defence",
    family: "Queen's Pawn",
    color: "black",
    eco: "D10",
    moves: ["d4", "d5", "c4", "c6"],
    popularity: 78,
  },
  {
    id: "b-semi-slav",
    name: "Semi-Slav",
    family: "Queen's Pawn",
    color: "black",
    eco: "D43",
    moves: ["d4", "d5", "c4", "c6", "Nf3", "Nf6", "Nc3", "e6"],
    popularity: 55,
  },
  {
    id: "b-qga",
    name: "Queen's Gambit Accepted",
    family: "Queen's Pawn",
    color: "black",
    eco: "D20",
    moves: ["d4", "d5", "c4", "dxc4"],
    popularity: 50,
  },
  {
    id: "b-benoni",
    name: "Benoni Defence",
    family: "Indian",
    color: "black",
    eco: "A60",
    moves: ["d4", "Nf6", "c4", "c5"],
    popularity: 38,
  },
  {
    id: "b-benko",
    name: "Benko Gambit",
    family: "Indian",
    color: "black",
    eco: "A57",
    moves: ["d4", "Nf6", "c4", "c5", "d5", "b5"],
    popularity: 30,
  },
  {
    id: "b-dutch",
    name: "Dutch Defence",
    family: "vs 1.d4",
    color: "black",
    eco: "A80",
    moves: ["d4", "f5"],
    popularity: 42,
  },
];

const BLACK_OTHER: CatalogEntry[] = [
  {
    id: "b-english-symmetric",
    name: "English Symmetric",
    family: "vs 1.c4",
    color: "black",
    eco: "A30",
    moves: ["c4", "c5"],
    popularity: 35,
  },
];

export const CATALOG: CatalogEntry[] = [
  ...WHITE_E4,
  ...WHITE_D4,
  ...WHITE_OTHER,
  ...BLACK_VS_E4,
  ...BLACK_VS_D4,
  ...BLACK_OTHER,
];

export const CATALOG_BY_ID: Record<string, CatalogEntry> = Object.fromEntries(
  CATALOG.map((e) => [e.id, e]),
);

export const UNCATEGORIZED_ID = "__uncategorized__";

export const UNCATEGORIZED_LABEL = "Uncategorized";
