// Curated directory of well-known chess accounts used to seed the landing
// page. Entries combine elite classical players, online blitz/bullet
// specialists, and major streamers/content creators so there's always
// someone interesting to click on. Where a handle isn't known on one
// platform we leave it undefined — the UI hides the corresponding chip.
//
// Country codes are ISO 3166-1 alpha-2. Titles follow FIDE conventions
// (GM/IM/FM/WGM/WIM/WFM/NM). Treat the list as a best-effort starting
// point — usernames can shift, so we'll iterate based on user reports.

export interface PopularPlayer {
  name: string;
  country: string;
  title?: string;
  lichess?: string;
  chesscom?: string;
  /** Freeform tag used for quick grouping in the UI. */
  tag?: "elite" | "streamer" | "top" | "content";
  note?: string;
}

export const POPULAR_PLAYERS: PopularPlayer[] = [
  // ──────────────────────────────────────────────────────────────
  // Super-elite — classical top 20ish
  // ──────────────────────────────────────────────────────────────
  { name: "Magnus Carlsen", country: "NO", title: "GM", lichess: "DrNykterstein", chesscom: "MagnusCarlsen", tag: "elite" },
  { name: "Hikaru Nakamura", country: "US", title: "GM", chesscom: "Hikaru", tag: "elite" },
  { name: "Fabiano Caruana", country: "US", title: "GM", chesscom: "FabianoCaruana", tag: "elite" },
  { name: "Gukesh Dommaraju", country: "IN", title: "GM", chesscom: "GukeshDommaraju", tag: "elite" },
  { name: "Ian Nepomniachtchi", country: "RU", title: "GM", lichess: "lachesisQ", chesscom: "lachesisQ", tag: "elite" },
  { name: "R Praggnanandhaa", country: "IN", title: "GM", chesscom: "rpragchess", tag: "elite" },
  { name: "Arjun Erigaisi", country: "IN", title: "GM", chesscom: "ArjunErigaisi", tag: "elite" },
  { name: "Alireza Firouzja", country: "FR", title: "GM", lichess: "alireza2003", chesscom: "alireza2003", tag: "elite" },
  { name: "Anish Giri", country: "NL", title: "GM", lichess: "AnishGiri", chesscom: "AnishGiri", tag: "elite" },
  { name: "Wesley So", country: "US", title: "GM", lichess: "WesleySo", chesscom: "GMWSO", tag: "elite" },
  { name: "Ding Liren", country: "CN", title: "GM", chesscom: "DingLiren", tag: "elite" },
  { name: "Levon Aronian", country: "US", title: "GM", chesscom: "LevonAronian", tag: "elite" },
  { name: "Maxime Vachier-Lagrave", country: "FR", title: "GM", lichess: "UnVieuxMonsieur", chesscom: "LyonBeast", tag: "elite" },
  { name: "Nodirbek Abdusattorov", country: "UZ", title: "GM", chesscom: "ChessWarrior7197", tag: "elite" },
  { name: "Vidit Gujrathi", country: "IN", title: "GM", chesscom: "viditchess", tag: "elite" },
  { name: "Nihal Sarin", country: "IN", title: "GM", lichess: "nihalsarin2004", chesscom: "nihalsarin", tag: "elite" },
  { name: "Leinier Dominguez", country: "US", title: "GM", chesscom: "LeinierDominguez", tag: "elite" },
  { name: "Jan-Krzysztof Duda", country: "PL", title: "GM", chesscom: "Polish_fighter3000", tag: "elite" },
  { name: "Vincent Keymer", country: "DE", title: "GM", chesscom: "Vincent_Keymer", tag: "elite" },
  { name: "Shakhriyar Mamedyarov", country: "AZ", title: "GM", chesscom: "ShakhTop", tag: "elite" },
  { name: "Teimour Radjabov", country: "AZ", title: "GM", chesscom: "Radjabov", tag: "elite" },
  { name: "Alexander Grischuk", country: "RU", title: "GM", chesscom: "Grischuk", tag: "elite" },
  { name: "Richard Rapport", country: "HU", title: "GM", chesscom: "RichardRapport", tag: "elite" },
  { name: "Yu Yangyi", country: "CN", title: "GM", chesscom: "YuYangyi", tag: "elite" },
  { name: "Wei Yi", country: "CN", title: "GM", chesscom: "WeiYi_LIFE", tag: "elite" },
  { name: "Parham Maghsoodloo", country: "IR", title: "GM", chesscom: "Parhamov", tag: "elite" },
  { name: "Dmitry Andreikin", country: "RU", title: "GM", chesscom: "2QQQ", tag: "elite" },
  { name: "Nijat Abasov", country: "AZ", title: "GM", chesscom: "Nijat_Abasov", tag: "elite" },
  { name: "Daniil Dubov", country: "RU", title: "GM", chesscom: "Duhless", tag: "elite" },
  { name: "Anton Korobov", country: "UA", title: "GM", chesscom: "AntonKorobov", tag: "elite" },
  { name: "Jorden van Foreest", country: "NL", title: "GM", chesscom: "JordenVanForeest", tag: "elite" },
  { name: "Vladislav Artemiev", country: "RU", title: "GM", chesscom: "vladimirovich9000", tag: "elite" },
  { name: "Nils Grandelius", country: "SE", title: "GM", chesscom: "nilsgrandelius", tag: "elite" },
  { name: "Sam Shankland", country: "US", title: "GM", chesscom: "GMShanky", tag: "elite" },
  { name: "Ray Robson", country: "US", title: "GM", chesscom: "2 praggnanandhaa" },
  { name: "Jeffery Xiong", country: "US", title: "GM", chesscom: "JefferyX", tag: "elite" },
  { name: "Hans Niemann", country: "US", title: "GM", chesscom: "Hansen", tag: "elite" },
  { name: "Awonder Liang", country: "US", title: "GM", chesscom: "awonderchess" },
  { name: "Sergey Karjakin", country: "RU", title: "GM", chesscom: "SergeyKarjakin", tag: "elite" },
  { name: "Peter Svidler", country: "RU", title: "GM", chesscom: "Peter_Svidler", tag: "elite" },

  // ──────────────────────────────────────────────────────────────
  // Online speed specialists / blitz grinders
  // ──────────────────────────────────────────────────────────────
  { name: "Andrew Tang", country: "US", title: "GM", lichess: "penguingm1", chesscom: "penguingim1", tag: "top" },
  { name: "Sergei Zhigalko", country: "BY", title: "GM", lichess: "Zhigalko_Sergei", chesscom: "Zhigalko_Sergei", tag: "top" },
  { name: "Vladislav Kovalev", country: "BY", title: "GM", lichess: "Konevlad", chesscom: "Konevlad", tag: "top" },
  { name: "Oleksandr Bortnyk", country: "UA", title: "GM", chesscom: "Oleksandr_Bortnyk", tag: "top" },
  { name: "Tuan Minh Le", country: "VN", title: "GM", chesscom: "liem_le", tag: "top" },
  { name: "José Martínez", country: "PE", title: "GM", chesscom: "jospem", tag: "top" },
  { name: "Andrey Esipenko", country: "RU", title: "GM", chesscom: "Andrey_Esipenko", tag: "top" },
  { name: "Alexey Sarana", country: "SRB", title: "GM", chesscom: "mhl_qgd", tag: "top" },
  { name: "Tigran Petrosian", country: "AM", title: "GM", chesscom: "TigranLPetrosian", tag: "top" },
  { name: "Denis Lazavik", country: "BY", title: "GM", chesscom: "DenLaz", tag: "top" },
  { name: "Volodar Murzin", country: "RU", title: "GM", chesscom: "Mishka_The_Great", tag: "top" },
  { name: "Rauf Mamedov", country: "AZ", title: "GM", chesscom: "Muisback", tag: "top" },
  { name: "Jules Moussard", country: "FR", title: "GM", chesscom: "Juleschess", tag: "top" },
  { name: "Yuriy Kuzubov", country: "UA", title: "GM", chesscom: "yurasikvatutin", tag: "top" },
  { name: "Maxim Matlakov", country: "RU", title: "GM", chesscom: "mml", tag: "top" },
  { name: "Baadur Jobava", country: "GE", title: "GM", chesscom: "Baadur_Jobava", tag: "top" },
  { name: "Vladimir Fedoseev", country: "SK", title: "GM", chesscom: "Bigfish1995", tag: "top" },
  { name: "Yanghao Ren", country: "CN", title: "GM", chesscom: "YangHaoRen" },
  { name: "Bassem Amin", country: "EG", title: "GM", chesscom: "bassem2007" },
  { name: "Ahmed Adly", country: "EG", title: "GM", chesscom: "GMAhmedAdly" },
  { name: "Jonas Bjerre", country: "DK", title: "GM", chesscom: "Atalik" },
  { name: "Alexey Shirov", country: "ES", title: "GM", chesscom: "alexeishirov", tag: "top" },
  { name: "Ivan Šarić", country: "HR", title: "GM", chesscom: "IvanShas" },
  { name: "Le Quang Liem", country: "VN", title: "GM", chesscom: "liem_le", tag: "top" },
  { name: "Bu Xiangzhi", country: "CN", title: "GM", chesscom: "BuXiangzhi" },
  { name: "Ni Hua", country: "CN", title: "GM", chesscom: "NiHua" },
  { name: "Yu Ruiyuan", country: "CN", title: "GM", chesscom: "yuruiyuan" },
  { name: "Sanan Sjugirov", country: "HU", title: "GM", chesscom: "SugarBoy" },
  { name: "Matthias Bluebaum", country: "DE", title: "GM", chesscom: "mblubi" },
  { name: "Daniel Fridman", country: "DE", title: "GM", chesscom: "daniel_fridman" },
  { name: "Alexander Donchenko", country: "DE", title: "GM", chesscom: "GMDonchenko" },
  { name: "David Howell", country: "GB", title: "GM", chesscom: "DavidHowell", tag: "top" },
  { name: "Michael Adams", country: "GB", title: "GM", chesscom: "Adamski" },
  { name: "Gawain Jones", country: "GB", title: "GM", chesscom: "GawainJones" },
  { name: "Luke McShane", country: "GB", title: "GM", chesscom: "LukeMcShane" },
  { name: "Salem Saleh", country: "AE", title: "GM", chesscom: "GMSaleM-ShabaaN" },
  { name: "Evgeny Tomashevsky", country: "RU", title: "GM", chesscom: "Tomashev" },
  { name: "Alexandr Predke", country: "RS", title: "GM", chesscom: "alexandr_predke" },
  { name: "Vladimir Fedoseev", country: "SK", title: "GM", chesscom: "Bigfish1995" },

  // ──────────────────────────────────────────────────────────────
  // Streamers & content creators (primary reach)
  // ──────────────────────────────────────────────────────────────
  { name: "Levy Rozman (GothamChess)", country: "US", title: "IM", chesscom: "GothamChess", tag: "streamer" },
  { name: "Eric Rosen", country: "US", title: "IM", lichess: "EricRosen", chesscom: "GMEricRosen", tag: "streamer" },
  { name: "Anna Cramling", country: "SE", title: "WFM", chesscom: "AnnaCramling", lichess: "AnnaCramling", tag: "streamer" },
  { name: "Alexandra Botez", country: "CA", title: "WFM", chesscom: "BotezLive", tag: "streamer" },
  { name: "Andrea Botez", country: "CA", chesscom: "AndreaBotez", tag: "streamer" },
  { name: "Eric Hansen (Chessbrah)", country: "CA", title: "GM", lichess: "Chessbrah", chesscom: "GMHansen", tag: "streamer" },
  { name: "Aman Hambleton", country: "CA", title: "GM", chesscom: "AmanHambleton", tag: "streamer" },
  { name: "Benjamin Finegold", country: "US", title: "GM", chesscom: "GMBenjaminFinegold", tag: "streamer" },
  { name: "Jan Gustafsson", country: "DE", title: "GM", chesscom: "GMJanGustafsson", tag: "streamer" },
  { name: "Laurent Fressinet", country: "FR", title: "GM", chesscom: "Mefisto1941", tag: "streamer" },
  { name: "Simon Williams (Ginger GM)", country: "GB", title: "GM", chesscom: "GingerGM", tag: "streamer" },
  { name: "Daniel King (PowerPlay)", country: "GB", title: "GM", chesscom: "DanielKing", tag: "streamer" },
  { name: "Daniel Rensch", country: "US", title: "IM", chesscom: "DanielRensch", tag: "streamer" },
  { name: "Robert Hess", country: "US", title: "GM", chesscom: "RobertHess", tag: "streamer" },
  { name: "David Pruess", country: "US", title: "IM", chesscom: "GMDavidPruess", tag: "streamer" },
  { name: "Jerry (ChessNetwork)", country: "US", title: "NM", chesscom: "ChessNetwork", lichess: "Chess-Network", tag: "streamer" },
  { name: "Anna Rudolf", country: "HU", title: "IM", chesscom: "AnnaRudolf", tag: "streamer" },
  { name: "Pia Cramling", country: "SE", title: "GM", chesscom: "PiaCramling" },
  { name: "Dina Belenkaya", country: "IL", title: "WGM", chesscom: "DinaBelenkaya", tag: "streamer" },
  { name: "Irina Krush", country: "US", title: "GM", chesscom: "krushchess" },
  { name: "Alexandra Kosteniuk", country: "CH", title: "GM", chesscom: "chessqueen" },
  { name: "Nemo Zhou", country: "CA", title: "WGM", chesscom: "NemoChess", tag: "streamer" },
  { name: "Qiyu Zhou", country: "CA", title: "WGM", chesscom: "akaNemsko", lichess: "akaNemo", tag: "streamer" },
  { name: "Divya Deshmukh", country: "IN", title: "IM", chesscom: "DivyaDeshmukh", tag: "streamer" },
  { name: "Tania Sachdev", country: "IN", title: "IM", chesscom: "TaniaSachdev" },
  { name: "Hou Yifan", country: "CN", title: "GM", chesscom: "HouYifan" },
  { name: "Sopiko Guramishvili", country: "GE", title: "IM", chesscom: "SopikoGuramishvili" },
  { name: "Elisabeth Pähtz", country: "DE", title: "GM", chesscom: "E-Paehtz" },
  { name: "Kanan Izzat", country: "AZ", title: "IM", chesscom: "ChessmeKANan", tag: "streamer" },
  { name: "Rafael Leitão", country: "BR", title: "GM", chesscom: "Santosleitao" },
  { name: "Alejandro Ramirez", country: "CR", title: "GM", chesscom: "GMAlejandroRamirez", tag: "streamer" },
  { name: "Anna Shukhman (aka Anna Shukhman)", country: "RU", title: "WGM", chesscom: "chessgeek98" },
  { name: "Arturs Neiksans", country: "LV", title: "GM", chesscom: "GMNeiksans", tag: "streamer" },
  { name: "Rafael Santos (Raffael Chess)", country: "BR", chesscom: "RaffaelChess", tag: "streamer" },
  { name: "Sergei Shipov (Crestbook)", country: "RU", title: "GM", chesscom: "crestbook", tag: "streamer" },
  { name: "Tamas Banusz", country: "HU", title: "GM", chesscom: "bancsoo", tag: "streamer" },
  { name: "Sergiusz Górski (NitroZyniak)", country: "PL", chesscom: "TheNitroZyniak", tag: "streamer" },
  { name: "Jonathan Li (JonLiMusic)", country: "US", chesscom: "JonLiMusic", tag: "streamer" },
  { name: "Oleksandr Zubov", country: "UA", title: "GM", chesscom: "ZubovOleksandr" },
  { name: "Aleksandra Maltsevskaya", country: "PL", title: "IM", chesscom: "AleksandraPL", tag: "streamer" },
  { name: "Christof Sielecki (ChessExplained)", country: "DE", title: "IM", chesscom: "ChessExplained", tag: "streamer" },
  { name: "Ben Feingold", country: "US", title: "GM", chesscom: "GMBenjaminFinegold", tag: "streamer" },
  { name: "Greg Shahade", country: "US", title: "IM", chesscom: "GregShahade" },
  { name: "John Bartholomew", country: "US", title: "IM", chesscom: "Fins0905", lichess: "Fins", tag: "streamer" },

  // ──────────────────────────────────────────────────────────────
  // Top women players
  // ──────────────────────────────────────────────────────────────
  { name: "Ju Wenjun", country: "CN", title: "GM", chesscom: "JuWenjun" },
  { name: "Aleksandra Goryachkina", country: "RU", title: "GM", chesscom: "Goryachkina" },
  { name: "Humpy Koneru", country: "IN", title: "GM", chesscom: "koneruhumpy" },
  { name: "Lei Tingjie", country: "CN", title: "GM", chesscom: "LeiTingjie" },
  { name: "Kateryna Lagno", country: "RU", title: "GM", chesscom: "KaterinaLagno" },
  { name: "Mariya Muzychuk", country: "UA", title: "GM", chesscom: "MariyaMuzychuk" },
  { name: "Anna Muzychuk", country: "UA", title: "GM", chesscom: "AnnaMuzychuk" },
  { name: "Harika Dronavalli", country: "IN", title: "GM", chesscom: "HARIKA2006" },
  { name: "Nana Dzagnidze", country: "GE", title: "GM", chesscom: "NanaDzagnidze" },
  { name: "Bibisara Assaubayeva", country: "KZ", title: "IM", chesscom: "bibisara_assaubayeva" },
  { name: "Vaishali R", country: "IN", title: "GM", chesscom: "VaishaliR" },
  { name: "Anna Zatonskih", country: "US", title: "IM", chesscom: "AnnaZatonskih" },
  { name: "Carissa Yip", country: "US", title: "GM", chesscom: "CarissaYip" },
  { name: "Jennifer Shahade", country: "US", title: "WGM", chesscom: "Shahade" },
  { name: "Alice Lee", country: "US", title: "IM", chesscom: "CubeLover12345" },

  // ──────────────────────────────────────────────────────────────
  // Regional strong GMs (a sample across countries)
  // ──────────────────────────────────────────────────────────────
  { name: "Daniel Dardha", country: "BE", title: "GM", chesscom: "Daniel_Dardha" },
  { name: "Bilel Bellahcene", country: "DZ", title: "GM", chesscom: "Bilel-Bellahcene" },
  { name: "Jose Eduardo Martinez Alcantara", country: "PE", title: "GM", chesscom: "jospem" },
  { name: "Leandro Krysa", country: "AR", title: "GM", chesscom: "LeandroKrysa" },
  { name: "Diego Flores", country: "AR", title: "GM", chesscom: "FloresDiego" },
  { name: "Alan Pichot", country: "AR", title: "GM", chesscom: "alanpichot" },
  { name: "Luis Paulo Supi", country: "BR", title: "GM", chesscom: "LPSupi" },
  { name: "Krikor Sevag Mekhitarian", country: "BR", title: "GM", chesscom: "Mekhitarian" },
  { name: "Alexander Ipatov", country: "ES", title: "GM", chesscom: "Ipatov" },
  { name: "David Antón Guijarro", country: "ES", title: "GM", chesscom: "DavidAnton" },
  { name: "Jaime Santos Latasa", country: "ES", title: "GM", chesscom: "JaimeSantosLatasa" },
  { name: "Fabien Libiszewski", country: "FR", title: "GM", chesscom: "Libiszewski" },
  { name: "Matthieu Cornette", country: "FR", title: "GM", chesscom: "Cornette" },
  { name: "Étienne Bacrot", country: "FR", title: "GM", chesscom: "Bacrot" },
  { name: "Romain Edouard", country: "FR", title: "GM", chesscom: "ChessMood" },
  { name: "Sebastien Maze", country: "FR", title: "GM", chesscom: "SebastienMaze" },
  { name: "Luke J McShane", country: "GB", title: "GM", chesscom: "LukeMcShane" },
  { name: "Nigel Short", country: "GB", title: "GM", chesscom: "NigelDShort" },
  { name: "Jules Moussard", country: "FR", title: "GM", chesscom: "Juleschess" },
  { name: "Vasyl Ivanchuk", country: "UA", title: "GM", chesscom: "Ivanchuk" },
  { name: "Pavel Eljanov", country: "UA", title: "GM", chesscom: "Eljanov" },
  { name: "Ruslan Ponomariov", country: "UA", title: "GM", chesscom: "Ponomariov" },
  { name: "Anton Kovalyov", country: "AR", title: "GM", chesscom: "Kovalyov" },
  { name: "Yuriy Kryvoruchko", country: "UA", title: "GM", chesscom: "Kryvoruchko" },
  { name: "Vadim Zvjaginsev", country: "RU", title: "GM", chesscom: "Zvjaginsev" },
  { name: "Lê Tuấn Minh", country: "VN", title: "GM", chesscom: "letuanminh" },
  { name: "Ehsan Ghaem Maghami", country: "IR", title: "GM", chesscom: "Ghaem" },
  { name: "Pouya Idani", country: "IR", title: "GM", chesscom: "pouyaidani" },
  { name: "M. Amin Tabatabaei", country: "IR", title: "GM", chesscom: "AminTabatabaei" },
  { name: "Ray Robson", country: "US", title: "GM", chesscom: "rayrobson" },
  { name: "Sam Sevian", country: "US", title: "GM", chesscom: "samsevian" },
  { name: "Daniel Naroditsky — remembered", country: "US", title: "GM", chesscom: "DanielNaroditsky", note: "RIP", tag: "content" },

  // ──────────────────────────────────────────────────────────────
  // Legends / notable veterans
  // ──────────────────────────────────────────────────────────────
  { name: "Garry Kasparov", country: "RU", title: "GM", chesscom: "STL_GarryKasparov" },
  { name: "Viswanathan Anand", country: "IN", title: "GM", chesscom: "viswanathan" },
  { name: "Vladimir Kramnik", country: "RU", title: "GM", chesscom: "vladimirkramnik" },
  { name: "Veselin Topalov", country: "BG", title: "GM", chesscom: "topalov" },
  { name: "Judit Polgar", country: "HU", title: "GM", chesscom: "PolgarJudit" },
  { name: "Boris Gelfand", country: "IL", title: "GM", chesscom: "GelfandBoris" },
  { name: "Vasilios Kotronias", country: "GR", title: "GM", chesscom: "kotroniasvasilios" },
  { name: "Sergey Tiviakov", country: "NL", title: "GM", chesscom: "tiviakov" },

  // ──────────────────────────────────────────────────────────────
  // Fast-rising juniors
  // ──────────────────────────────────────────────────────────────
  { name: "Faustino Oro", country: "AR", title: "IM", chesscom: "faustino_oro", tag: "top" },
  { name: "Abhimanyu Mishra", country: "US", title: "GM", chesscom: "AbhimanyuMishra", tag: "top" },
  { name: "Volodar Murzin", country: "RU", title: "GM", chesscom: "Mishka_The_Great", tag: "top" },
  { name: "Pranav V", country: "IN", title: "GM", chesscom: "pranavv2006" },
  { name: "Ilia Iljushenok", country: "RU", title: "GM", chesscom: "iljiushenok" },
  { name: "Aydin Suleymanli", country: "AZ", title: "GM", chesscom: "AydinSuleymanli" },
  { name: "Frederik Svane", country: "DE", title: "GM", chesscom: "FrederikSvane" },
  { name: "Rudik Makarian", country: "RU", title: "GM", chesscom: "Glory_Makarian" },
  { name: "Polina Shuvalova", country: "RU", title: "IM", chesscom: "PolinaShuvalova" },
  { name: "Zhu Jiner", country: "CN", title: "IM", chesscom: "JinerZhu" },
  { name: "Savitha Shri B", country: "IN", title: "IM", chesscom: "savithasri" },

  // ──────────────────────────────────────────────────────────────
  // Smaller streamers / community regulars
  // ──────────────────────────────────────────────────────────────
  { name: "Hikaru Nakamura (alt — Nakamura)", country: "US", title: "GM", chesscom: "GMHikaru", tag: "streamer" },
  { name: "James Canty III", country: "US", title: "FM", chesscom: "JamesCantyIII", tag: "streamer" },
  { name: "Qiyu Zhou (akaNemsko)", country: "CA", title: "WGM", chesscom: "akaNemsko", tag: "streamer" },
  { name: "Alex Banzea", country: "RO", title: "IM", chesscom: "FmAlex", tag: "streamer" },
  { name: "Andras Toth", country: "HU", title: "IM", chesscom: "AndrasToth", tag: "streamer" },
  { name: "Alex Colovic", country: "MK", title: "GM", chesscom: "AlexColovic", tag: "streamer" },
  { name: "Peter Leko", country: "HU", title: "GM", chesscom: "PeterLeko", tag: "streamer" },
  { name: "Maurice Ashley", country: "JM", title: "GM", chesscom: "MauriceAshley", tag: "streamer" },
  { name: "Daniel Shapiro", country: "US", title: "FM", chesscom: "DShap", tag: "streamer" },
  { name: "Ben Johnson (PerpetualChess)", country: "US", chesscom: "PerpetualChess", tag: "streamer" },
  { name: "International Master Hans Schut", country: "NL", title: "IM", chesscom: "HansSchut" },
  { name: "Aagaard (Quality Chess)", country: "SE", title: "GM", chesscom: "aagaard" },
  { name: "Alex Yermolinsky", country: "US", title: "GM", chesscom: "GMYermo" },
  { name: "Tryfon Gavriel (Kingscrusher)", country: "GB", title: "FM", lichess: "Kingscrusher", chesscom: "Kingscrusher", tag: "streamer" },
  { name: "Sam Copeland", country: "US", title: "IM", chesscom: "SamCopeland", tag: "streamer" },
  { name: "Gata Kamsky", country: "US", title: "GM", chesscom: "Gata" },
  { name: "Alejandro Ramirez", country: "CR", title: "GM", chesscom: "GMAlejandroRamirez" },
  { name: "Yasser Seirawan", country: "US", title: "GM", chesscom: "GMYasserSeirawan" },
  { name: "Maxim Dlugy", country: "US", title: "GM", chesscom: "MaximDlugy" },
  { name: "Jean-Pierre Le Roux", country: "FR", title: "GM", chesscom: "JeanPierre" },
  { name: "Tigran L. Petrosian", country: "AM", title: "GM", chesscom: "GMTigranPetrosian" },
  { name: "Mikheil Mchedlishvili", country: "GE", title: "GM", chesscom: "misha63" },
  { name: "Daniel Stellwagen", country: "NL", title: "GM", chesscom: "stellwagen" },
  { name: "Liviu-Dieter Nisipeanu", country: "DE", title: "GM", chesscom: "lnisipeanu" },
  { name: "Francisco Vallejo Pons", country: "ES", title: "GM", chesscom: "nigalsag" },
  { name: "Paco Vallejo Pons", country: "ES", title: "GM", chesscom: "FVallejo" },
  { name: "Constantin Lupulescu", country: "RO", title: "GM", chesscom: "lupulescu" },
  { name: "Liviu Oprisor", country: "RO", title: "GM", chesscom: "lorand" },
  { name: "Emil Sutovsky", country: "IL", title: "GM", chesscom: "sutovsky" },
  { name: "Ilia Smirin", country: "IL", title: "GM", chesscom: "smirin" },
  { name: "Evgeny Postny", country: "IL", title: "GM", chesscom: "Postny" },
  { name: "Baskaran Adhiban", country: "IN", title: "GM", chesscom: "thechesspuffin" },
  { name: "S.P. Sethuraman", country: "IN", title: "GM", chesscom: "sethuraman" },
  { name: "Surya Shekhar Ganguly", country: "IN", title: "GM", chesscom: "suryaindian" },
  { name: "Krishnan Sasikiran", country: "IN", title: "GM", chesscom: "sasikirankrishnan" },
  { name: "Parimarjan Negi", country: "IN", title: "GM", chesscom: "parimarjan" },
  { name: "Abhijeet Gupta", country: "IN", title: "GM", chesscom: "indianchess" },
  { name: "Aravindh Chithambaram", country: "IN", title: "GM", chesscom: "GMAravindh" },
  { name: "Raunak Sadhwani", country: "IN", title: "GM", chesscom: "raunak-sadhwani" },
  { name: "Aryan Chopra", country: "IN", title: "GM", chesscom: "aryanchopra" },
  { name: "Pentala Harikrishna", country: "IN", title: "GM", chesscom: "PHarikrishna" },
  { name: "Baadur Jobava", country: "GE", title: "GM", chesscom: "Jobava_B" },
  { name: "Zurab Azmaiparashvili", country: "GE", title: "GM", chesscom: "Azmaiparashvili" },
  { name: "Levan Pantsulaia", country: "GE", title: "GM", chesscom: "Pantsulaia" },
  { name: "Denis Khismatullin", country: "RU", title: "GM", chesscom: "khisma" },
  { name: "Nikita Vitiugov", country: "GB", title: "GM", chesscom: "nikitavitiugov" },
  { name: "Maxim Rodshtein", country: "IL", title: "GM", chesscom: "rodshtein" },
  { name: "Boris Grachev", country: "RU", title: "GM", chesscom: "Grach" },
  { name: "Ediz Gurel", country: "TR", title: "IM", chesscom: "EdizGurel", tag: "top" },
  { name: "Yagiz Kaan Erdogmus", country: "TR", title: "GM", chesscom: "YagizKaanE", tag: "top" },
  { name: "Ediz Gurel", country: "TR", title: "IM", chesscom: "edizgurel" },
  { name: "Mustafa Yilmaz", country: "TR", title: "GM", chesscom: "mustafayilmaz" },
  { name: "Emre Can", country: "TR", title: "GM", chesscom: "emreC" },
  { name: "Santosh Gujrathi Vidit", country: "IN", title: "GM", chesscom: "viditchess" },
  { name: "Magesh Chandran Panchanathan", country: "US", title: "GM", chesscom: "magesh" },
  { name: "Tamir Nabaty", country: "IL", title: "GM", chesscom: "Nabaty" },
  { name: "Markus Ragger", country: "AT", title: "GM", chesscom: "Raggermarkus" },
  { name: "Felix Blohberger", country: "AT", title: "IM", chesscom: "Blohberger" },
  { name: "Gabriel Sargissian", country: "AM", title: "GM", chesscom: "Sargissian" },
  { name: "Hrant Melkumyan", country: "AM", title: "GM", chesscom: "Melkumyan" },
  { name: "Sergei Movsesian", country: "AM", title: "GM", chesscom: "Movsesian" },
  { name: "Haik Martirosyan", country: "AM", title: "GM", chesscom: "MarHaik2" },
  { name: "Manuel Petrosyan", country: "AM", title: "GM", chesscom: "Manyka" },
  { name: "Aram Hakobyan", country: "AM", title: "GM", chesscom: "AramHakobyan" },
  { name: "Robert Hovhannisyan", country: "AM", title: "GM", chesscom: "Rob_hov" },
  { name: "Karen Grigoryan", country: "AM", title: "GM", chesscom: "Karen-Grigoryan" },
  { name: "Kirill Shevchenko", country: "RO", title: "GM", chesscom: "Shevchenko_K" },
  { name: "Andrey Vovk", country: "UA", title: "GM", chesscom: "VovkAndrey" },
  { name: "Yuriy Zinchenko", country: "UA", title: "GM", chesscom: "Zinchenko" },
  { name: "Marin Bosiocic", country: "HR", title: "GM", chesscom: "bosiocic" },
  { name: "Robert Markuš", country: "RS", title: "GM", chesscom: "RobertMarkus" },
  { name: "Matthieu Cornette", country: "FR", title: "GM", chesscom: "MatCorn" },
  { name: "Maxime Lagarde", country: "FR", title: "GM", chesscom: "MaximeLagarde" },
  { name: "Tigran Gharamian", country: "FR", title: "GM", chesscom: "gharamianTigran" },
];

export function playerCountries(): string[] {
  const set = new Set<string>();
  for (const p of POPULAR_PLAYERS) set.add(p.country);
  return Array.from(set).sort();
}
